import puppeteer from 'puppeteer';
import { marked } from 'marked';
import { Document, Packer, Paragraph, Table, TableRow, TableCell, HeadingLevel, BorderStyle, WidthType } from 'docx';
import { stripIntroductionSection, stripConversationalPleasantries, parseTextWithBold } from './chapter.parser';

/**
 * Renders corporate styled PDF buffer from raw markdown string.
 */
export async function exportToPDF(title: string, author: string, text: string): Promise<Buffer> {
  const cleanedText = stripConversationalPleasantries(stripIntroductionSection(text));
  const rawHtmlContent = await marked(cleanedText);

  const fullHtml = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>${title}</title>
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
      <style>
        body {
          font-family: 'Inter', 'Helvetica Neue', Helvetica, Arial, sans-serif;
          line-height: 1.6;
          color: #1f2937;
          margin: 0;
          padding: 40px;
          font-size: 14px;
          background-color: #ffffff;
        }
        .top-bar {
          display: flex;
          justify-content: space-between;
          font-size: 11px;
          color: #6b7280;
          border-bottom: 1px solid #e5e7eb;
          padding-bottom: 8px;
          margin-bottom: 24px;
          text-transform: uppercase;
          letter-spacing: 0.05em;
          font-weight: 500;
        }
        .doc-title {
          font-size: 28px;
          font-weight: 700;
          color: #111827;
          margin: 0 0 30px 0;
          line-height: 1.2;
        }
        h1, h2, h3 {
          color: #111827;
          font-weight: 600;
          margin-top: 24px;
          margin-bottom: 12px;
        }
        h1 { font-size: 20px; border-bottom: 1px solid #f3f4f6; padding-bottom: 5px; }
        h2 { font-size: 16px; }
        h3 { font-size: 14px; }
        p {
          margin-top: 0;
          margin-bottom: 16px;
        }
        blockquote {
          margin: 0 0 16px 0;
          padding: 8px 16px;
          border-left: 4px solid #e5e7eb;
          background-color: #f9fafb;
          color: #4b5563;
          font-style: italic;
        }
        ul, ol {
          margin-top: 0;
          margin-bottom: 16px;
          padding-left: 24px;
        }
        li {
          margin-bottom: 4px;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          margin-top: 16px;
          margin-bottom: 16px;
          font-size: 13px;
        }
        th, td {
          border: 1px solid #e5e7eb;
          padding: 10px 12px;
          text-align: left;
        }
        th {
          background-color: #f3f4f6;
          font-weight: 600;
          color: #374151;
        }
        tr:nth-child(even) td {
          background-color: #f9fafb;
        }
      </style>
    </head>
    <body>
      <div class="top-bar">
        <span>Generated by: ${author}</span>
        <span>Date: ${new Date().toLocaleDateString()}</span>
      </div>
      <h1 class="doc-title">${title}</h1>
      <div class="content">
        ${rawHtmlContent}
      </div>
    </body>
    </html>
  `;

  const browser = await puppeteer.launch({
    headless: true,
    executablePath: process.env.NODE_ENV === 'production' ? '/usr/bin/chromium' : undefined,
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-dev-shm-usage',
      '--disable-gpu',
      '--no-first-run',
      '--no-zygote',
      '--disable-extensions'
    ]
  });
  try {
    const page = await browser.newPage();
    await page.setContent(fullHtml, { waitUntil: 'networkidle0' });
    const pdfBuffer = await page.pdf({
      format: 'A4',
      margin: {
        top: '20mm',
        bottom: '20mm',
        left: '20mm',
        right: '20mm'
      },
      printBackground: true
    });
    return pdfBuffer;
  } finally {
    await browser.close();
  }
}

/**
 * Renders corporate styled Word Document buffer from raw markdown string.
 */
export function exportToDOCX(title: string, author: string, text: string): Promise<Buffer> {
  const noIntroText = stripIntroductionSection(text);
  const cleanedText = stripConversationalPleasantries(noIntroText);
  const lines = cleanedText.split('\n');
  const docChildren: any[] = [];

  // Add Document Title
  docChildren.push(new Paragraph({
    text: title,
    heading: HeadingLevel.TITLE,
    spacing: { after: 150 }
  }));

  // Add Document Metadata
  docChildren.push(new Paragraph({
    children: parseTextWithBold(`Generated by: ${author} | Date: ${new Date().toLocaleDateString()}`),
    spacing: { after: 350 }
  }));

  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    const trimmed = line.trim();

    if (!trimmed) {
      i++;
      continue;
    }

    // Parse Markdown Tables
    if (trimmed.startsWith('|')) {
      const tableLines: string[] = [];
      while (i < lines.length && lines[i].trim().startsWith('|')) {
        tableLines.push(lines[i].trim());
        i++;
      }

      const rows: string[][] = [];
      for (const tLine of tableLines) {
        if (tLine.includes('---') || tLine.includes('===') || /^[|\s-]+$/.test(tLine)) {
          continue;
        }
        const cells = tLine.split('|').map(c => c.trim()).filter((_, idx, arr) => idx > 0 && idx < arr.length - 1);
        if (cells.length > 0) {
          rows.push(cells);
        }
      }

      if (rows.length > 0) {
        const tableRows = rows.map((rowCells, rIdx) => {
          return new TableRow({
            children: rowCells.map(cellText => {
              return new TableCell({
                children: [
                  new Paragraph({
                    children: parseTextWithBold(cellText, { defaultBold: rIdx === 0 })
                  })
                ],
                shading: rIdx === 0 ? { fill: 'F3F4F6' } : undefined,
                margins: {
                  top: 120,
                  bottom: 120,
                  left: 150,
                  right: 150
                }
              });
            })
          });
        });

        const docxTable = new Table({
          rows: tableRows,
          width: {
            size: 100,
            type: WidthType.PERCENTAGE
          },
          borders: {
            top: { style: BorderStyle.SINGLE, size: 6, color: 'E5E7EB' },
            bottom: { style: BorderStyle.SINGLE, size: 6, color: 'E5E7EB' },
            left: { style: BorderStyle.SINGLE, size: 6, color: 'E5E7EB' },
            right: { style: BorderStyle.SINGLE, size: 6, color: 'E5E7EB' },
            insideHorizontal: { style: BorderStyle.SINGLE, size: 6, color: 'E5E7EB' },
            insideVertical: { style: BorderStyle.SINGLE, size: 6, color: 'E5E7EB' }
          }
        });

        docChildren.push(docxTable);
        docChildren.push(new Paragraph({ spacing: { after: 150 } }));
      }
      continue;
    }

    // Parse Markdown Headers
    if (trimmed.startsWith('###')) {
      docChildren.push(new Paragraph({
        text: trimmed.replace('###', '').trim(),
        heading: HeadingLevel.HEADING_3,
        spacing: { before: 180, after: 90 }
      }));
    } else if (trimmed.startsWith('##')) {
      docChildren.push(new Paragraph({
        text: trimmed.replace('##', '').trim(),
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 250, after: 120 }
      }));
    } else if (trimmed.startsWith('#')) {
      docChildren.push(new Paragraph({
        text: trimmed.replace('#', '').trim(),
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 350, after: 180 }
      }));
    } else if (trimmed.startsWith('>')) {
      // Parse Blockquotes
      const runs = parseTextWithBold(trimmed.substring(1).trim(), { italics: true, color: '555555' });
      docChildren.push(new Paragraph({
        children: runs,
        spacing: { before: 80, after: 80 }
      }));
    } else if (trimmed.startsWith('-') || trimmed.startsWith('•') || trimmed.startsWith('*')) {
      // Parse Bullet Lists
      const bulletText = trimmed.replace(/^[-•*]\s*/, '');
      docChildren.push(new Paragraph({
        children: parseTextWithBold(bulletText),
        bullet: {
          level: 0
        },
        spacing: { after: 100 }
      }));
    } else {
      // Parse Regular Paragraphs
      docChildren.push(new Paragraph({
        children: parseTextWithBold(trimmed),
        spacing: { after: 100 }
      }));
    }

    i++;
  }

  const doc = new Document({
    sections: [{
      properties: {},
      children: docChildren
    }]
  });

  return Packer.toBuffer(doc);
}
